<a href="https://colab.research.google.com/github/snig-17/COMP0014/blob/main/Lab1a_programming_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programming Notebook

This is a simple notebook to help you get started with programming in Python, and get used to using Jupyter notebooks with embedded python functions.

## 1. Printing

Run the following code snippet (using the "Run" button at the top or by pressing Shift+Enter while the below box is active) in order to print out a message. See what happens!

In [1]:
print("Hello world")

Hello world


**Exercise: Print your own message.**

Use the empty code box below to print your own message. (After you finish writing your code, be sure to run it!)

In [2]:
print("Hello")

Hello


## 2. Variables

Another important part of programming is the language to define variables. Variables are named "boxes" where you can store data and later alter/overwrite or retrieve that data by using the name of that variable. The following example makes two variables, x and y, sets their values, and then prints them out. The first variable is set to a number and the second is set to a string. Notice that Python allows you to handle numerical and string data in very similar ways.

In [3]:
x = 3
y = "Hi"

print("The value of x is", x, "and the value of y is", y)

The value of x is 3 and the value of y is Hi


Also note that Python automatically inserts spaces in between comma-separated values when they are sent into the `print` function.

**Exercise: Use the above information to print out the value of 3841 * .0192.**

Given what you have learned above, write some code in the below box to print out the result of multiplying 3841 by .0192. You can do this using the `print` function directly, or you can use variables in order to do the calculation.

(If needed, here's [a guide on how to write arithmetic operators in Python](https://www.w3schools.com/python/gloss_python_arithmetic_operators.asp).)

In [4]:
print(3841 * .0192)

73.74719999999999


## 3. Taking and using user input

In Python, you can use the `input()` function in order to collect input from the user. You can then use that information in the form of a variable in order to make the program behave differently depending on what the user has input. For example, the below function, prints out whether the number input is greater than 10.

In [5]:
# This prompts the user to input something
# (This is a comment, by the way. Anything after the '#' is ignored/skipped by Python.)
user_input = input('Enter a number:')

if (float(user_input) > 10):
    # Note that this will throw an error if you don't enter a number.
    # You can fix this behavior if you want (you will probably want to use a try/except),
    # but you don't have to.
    print("Your number is greater than 10!")
elif (float(user_input) >= 0):
    # "else if" -- If the first condition didn't hold but this one did.
    # Also, note that putting ':' after if/elif/else is important.
    print("Your number is not greater than 10...")
else:
    # If none of the above conditions held...
    print("Your number is negative.")

Enter a number:5
Your number is not greater than 10...


**Exercise: Run the above code several times with different inputs.**

Experiment with inputting different values to reach each of the conditions and try out unusual values to see what happens.

## 4. Defined functions

Just like with variables, sometimes it is helpful to write named bits of code that can later be invoked (or *called*) by using the name they have been given. This allows us to reuse the same set of work, sometimes under differing situations. For example, functions can take *arguments*, or input variables, that they make use of when operating, and which change the work they do.

For example, the following function prints out the modulus of the two values sent into it:

In [6]:
# First we have to define our function:

def modulus(a, b): # a and b are arguments. Note the colon needed at the end.
    # Note: in Python, indentation is meaningful/important. In particular, it marks what
    # lines of code belong to the body of a function or if/for/while/etc. block.
    print(a % b)

# Now we are outside the function body.
# Now that we have defined the function, we can use it as much as we like.

modulus(10, 3)
modulus(13, 7)
modulus(-1, 3)

1
6
2


Instead of printing, we could actually `return` a value. Whatever is returned by a function can be used in another function or stored within a variable for later use. See below for the variable usage:

In [7]:
def modulus(a, b):
    return a % b  # <-- this is different

myvar = modulus(20, 5)
print(myvar)

0


**Exercise: Alter the above code to stick the result of the modulus function directly into a function**

You can put it inside a `print` function, or you can use some other function.

## 5. For loops

For loops are one way in which you can repeatedly execute some code over and over until some end condition is met (the other way is `while` loops). In order to use a for loop, you usually have some kind of variable or iterator you set up, and then when the variable crosses a threshold or the iterator reaches the end of the data structure it's traveling through, then the for loop exits. In Python, there are quite a few ways to set up for loops.

The below example shows one of the most basic types of Python loops, which is using the function `range()`. Range takes one, two, or three numbers. When it takes just one, it generates a sequence starting from 0 and going up to the largest integer smaller than the given number, which may not be what you're expecting. Specifying two numbers allows you to set the starting number as well as the top. See more information about `range` [here](https://docs.python.org/3/library/stdtypes.html#range).

In [8]:
my_sum = 0

for i in range(5):
    my_sum += i # This increments my_sum by i; it is equivalent to saying "my_sum = my_sum + i"
    print(i)

# After the for loop, print the total:
print(my_sum)

0
1
2
3
4
10


**Exercise: Use what you have learned above to create a program that takes in two values from the user, `a` and `b`, and returns the sum, a + a+1 + a+2 + ... + b**

In [21]:
# Use user_input (twice)
# Create a function with a for loop

a = int(input("Enter a number a: "))
b = int(input("Enter a number b: "))


def sum(a,b):
  sum = 0
  for i in range(0, b-a+1):
    print(a+i)
    sum += a+i
  return sum

sum(a,b)


Enter a number a: 4
Enter a number b: 7
4
5
6
7


22

## 6. Python arrays (lists)

One very important part of Python is that it has a construct called lists that allows multiple pieces of data to be collected together in the form of an array whose data can be accessed by their position within the array. For example, the following code constructs a list and then prints the first and third elements.

In [22]:
my_arr = [1, "Hi", "green", -2.3]

print(my_arr[0])
print(my_arr[2])

1
green


Note that arrays can contain data of different types all mixed together.

The data in arrays can also be accessed by *iterating* through all of the elements one by one starting from the first. The below function does so using an iterator variable (`i`) and the construction `for i in x`.

In [23]:
def print_elements(x):
    for i in x:  # Each "i" here represents a different element of the array each time we loop
        print(i)

my_arr = [10, 8, 3, 1, 2]
print_elements(my_arr)

10
8
3
1
2


**Exercise: Using what you have learned so far, alter the above function to do the same thing, but by using the indexes of the array, not the iterator i.**

In order to do this, you may want to get the number of elements in the array, which can be retrieved using `len(x)`, where `x` is the name of an array variable.

## 7. Python dictionaries

Another important data structure used in Python are dictionaries, which are a set of key-value pairs. Like arrays, they store multiple pieces of data, but unlike arrays, the data is accessed by using the name (key) of the piece of data. The following example shows how a dictionary is created and its values accessed.

In [24]:
my_dict = {
    "red": 50,
    "green": 192,
    "blue": 127
}

print(my_dict["blue"])

127


Note: Even though the values in the above example are all numbers, you can put any kind of data as the values of a dictionary, and they don't need to match. The keys of a dictionary, however, should all be strings.

The following shows how you can iterate through dictionaries, while being able to manipulate both key and value data at the same time:

In [25]:
# Note: This code snippet will not run unless you run the previous code snippet.
# The previous code snippet defines the variable "my_dict" so without running that
# one first, THIS code snippet has no idea what "my_dict" is...
for k, v in my_dict.items():
    print("The value of key", k, "is", v)

The value of key red is 50
The value of key green is 192
The value of key blue is 127


**Exercise: Make your own dictionary and print out its values**

Also, a bit more difficult, but you may want to try out adding a NEW key-value pair to a dictionary after it has already been created.

In [27]:
dict = {"A": 1,
        "B": 2,
        "C": 3}

def print_dict(x):
  for k, v in x.items():
    print("The value of key", k, "is", v)

print_dict(dict)


The value of key A is 1
The value of key B is 2
The value of key C is 3


## 8. The numpy library and numpy arrays

Numpy is a popular library useful for mathematical functions. In particular, it specializes in working with matrix data that is needed for linear algebra applications, which machine learning is largely based on. In order to make use of the numpy library, we must first import it. We do that in Python using the following code:

In [28]:
import numpy as np

If you run the above code box, it will appear to do nothing. However, by running that box, we can now make use of numpy functions. The `as np` part of that line of code gives us a nickname we can use to refer to the numpy module. Normally, we would need to say `numpy.array()` if we wanted to make a numpy array, but with the nickname, we can just say `np.array()` (this is useful when importing libraries and sub-modules with long names, not so useful here). Typically, `import` lines are collected together and placed at the top of Python files/notebooks so that all of the necessary libraries can be loaded all at once and used from that point onward. I did not do that here, though, because I wanted to wait until this point to introduce what libraries are.

The tricky part of using numpy is that it defines its own set of arrays with their own functionality and convenience features. These arrays are separate from the Python arrays (lists) discussed above, and they behave in different ways. It's important, therefore, to keep track of whether a piece of data is a Python array or a numpy array.

The following example shows how to create multidimensional (nested) Python arrays and numpy arrays, and how they behave differently.

In [29]:
x = [[1, 2, 3], [4, 5, 6]]
print(x[1]) # prints [4, 5, 6]
print(x[0][2]) # prints 3

# Remember: You can't properly run this line UNLESS you've run the box with the
# import line above! (And you only need to run the above once and can use it
# multiple times thereafter.)
y = np.array([[1, 2, 3], [4, 5, 6]])
print(y[1]) # prints [4 5 6]
print(y[0][2]) # prints 3

[4, 5, 6]
3
[4 5 6]
3


In [30]:
# These two lines will yield a TypeError. Uncomment them to see what happens.
#print(x[:, 1])
#print(x[1, :])

print(y[:, 1]) # prints [2 5]
print(y[1, :]) # prints [4 5 6]

[2 5]
[4 5 6]


In [31]:
print(x)
print(y)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [32]:
print(type(x)) # x is a Python list
print(type(y)) # y is a numpy array (numpy.ndarray -- n-dimensional array)

<class 'list'>
<class 'numpy.ndarray'>


**Exercise: In the codebox below, use numpy to create a big, multidimensional array**

You may want to check out the [numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) function. This is a popular function for creating an empty (zero) array with particular dimensions. See the page linked for some examples of how to use the "shape" parameter in order to determine the dimensions of the created array. Then try printing it to verify the size and contents!

In [38]:
z = [[[1, 2, 3],
      [4, 5]],
    [6, 7, 8, 9]]
print(z)


[[[1, 2, 3], [4, 5]], [6, 7, 8, 9]]


## 9. Classes and objects

Python is an object-oriented language. Object-oriented languages allow you to define custom data types called *classes* that come bundled with them (1) member data (variables associated with this class/with objects of this type), and (2) member functions (named functions that operate on objects of this type and determine their specialized behavior).

So, for example, let's say I wanted to create an object that represents the result of a division (say 5 / 3), but I don't want to just have the decimal result (1.6666...) but instead keep the quotient and remainder (1 and 2) around. I could do this using a custom class that I build/define. The below shows how to do this:

In [60]:
class DivisionResult():
    def __init__(self, dividend, divisor):
        # This copies the two arguments into member variables with the same name
        self.dividend = dividend
        self.divisor = divisor

        # In addition, I want to store two more member variables.
        # (I am basically allowed to make up member variables as I go.)
        self.quotient = dividend // divisor
        self.remainder = dividend % divisor

    def print_mixed_fraction(self):
      print(self.quotient, self.remainder,"/",self.dividend)



Running the above piece of code again does not seem to do anything. But from now on, we can make use of this `DivisionResult` class we just defined.

Note that I have defined a function called `__init__`. This is a special function called a constructor. Constructors run when a new object of this class's type is first created (*instantiated*). The first argument in the `__init__` function is `self`, which is a special variable representing the created object itself. So when I say `self.dividend = dividend`, it is essentially copying the value of `dividend`, which is sent into the constructor, into the data that this object always keeps around with it (its *member data* or *member variables*).

Let's try using our new `DivisionResult` class!

In [61]:
a = DivisionResult(5, 3) # We only pass in two arguments: dividend and divisor. We do not need
                         # to pass in "self"; that is prepended automatically.

print(a.dividend)
print(a.quotient)
print(a.remainder)

5
1
2


Cool, huh?

**Exercise: Try adding a new function to the above DivisionResult class definition, called `print_mixed_fraction`.**

When called using the below code, this function should print out the value of the division result in the form of a mixed fraction (e.g. 1 2/3). Hint: the `print_mixed_fraction` function should take no arguments (aside from the "self" that gets automatically prepended). Also, if you want more flexibility in using Python's `print` function, you may want check out [guides like this one](https://learnpython.com/blog/python-print-function/).

In [62]:
a.print_mixed_fraction()  # After rerunning your altered class definition and the variable declaration
                          # above, run this to to test the behavior of the function you wrote.

1 2 / 5


Okay, that is it for this very simple introduction to programming in Python. Hopefully it is enough for you to get started with the main notebooks. If you have any questions, just ask!